logging:
  level:
    org:
      springframework:
        jdbc:
          core: info

site:
  domain: http://localhost:8080

# H2
spring:
  profiles:
    include: email
  devtools:
    restart:
      enabled: true
    livereload:
      enabled: true
  h2:
    console:
      enabled: true
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    database-platform: org.hibernate.dialect.H2Dialect
  datasource:
    url: jdbc:h2:mem:testdb;MODE=MYSQL
    username: sa
    password:
    driver-class-name: org.h2.Driver
  session:
    store-type: jdbc